runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /populateDatabase
  script: main.app
  login: admin
- url: /.*
  script: main.app
  login: required

libraries:
- name: jinja2
  version: latest
- name: PIL
  version: 1.1.7
  #
# http://localhost:8080/_ah/login
